default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  socket: /var/run/mysqld/mysqld.sock
  redis:
    host: localhost
    port: 6379
    db: 0
    options:
      namespace: project-gshock

development:
  <<: *default
  database: project_gshock